version: '3.8'

services:
  mysqldb:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: SkiStationDB
    ports:
      - "3307:3306"
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    volumes:
      - ./volumes/nexus_data:/nexus-data

  jenkins:
    image: custom_jenkins:latest
    container_name: jenkins
    privileged: true
    user: "1000:1000"
    ports:
      - "8082:8080"
    volumes:
      - ./volume/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


  sonarqube:
    image: sonarqube:latest
    depends_on:
      - sonardb
    ports:
      - "9002:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonardb:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./volumes/sonarqube_data:/opt/sonarqube/data
      - ./volumes/sonarqube_logs:/opt/sonarqube/logs
      - ./volumes/sonarqube_temp:/opt/sonarqube/temp

  sonardb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
      - ./volumes/postgresql_data:/var/lib/postgresql/data


  SkiStationProject:
    build: .
    restart: always
    image: skiapp
    environment:
      spring.datasource.url: "jdbc:mysql://mysqldb:3306/SkiStationDB?createDatabaseIfNotExist=true"
      spring.datasource.username: root
      spring.datasource.password: password
    container_name: skicontainer
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb

volumes:
  mysql_data: